server:
  port: 8081
logging:
  config: classpath:logback.xml

xxl-job:
  admin:
    address: http://127.0.0.1:8080/xxl-job-admin
    access-token: default_token
  executor:
    app-name: xxl-job-executor-sample
    ip: 127.0.0.1